FROM node:8.15.0-jessie

# Create a working directory
WORKDIR /usr/src/app

# Install all dependencies
COPY package*.json ./

RUN npm install

# Bundle App Source
COPY . .

# Start the node application
CMD ["npm", "start"]